export const ActionTypes = {
    ADD_QUANTITY: "ADD_QUANTITY",
    DELETE_QUANTITY: "DELETE_QUANTITY",
    RESTART_QUANTITY: "RESTART_QUANTITY",
    TOGGLE_BASKET: "TOGGLE_BASKET",
    ACTIVE_BASKET: "ACTIVE_BASKET",
    SET_IMAGE: "SET_IMAGE",
    LIGHTBOX_SHOW: "LIGHTBOX_SHOW",
    LIGHTBOX_HIDE: "LIGHTBOX_HIDE",
    INCREASE_ID: "INCREASE_ID",
    DECREASE_ID: "DECREASE_ID",
}